### ISSUE TITLE
notify("You cannot hold a weapon in a safe zone.", "error")

### ISSUE THREAD

**Issue by PWajong** [Fancazista/fanca_safezone#2]
the notify keeps spamming.... 

![image](https://github.com/Fancazista/fanca_safezone/assets/135458250/77643b55-8f1c-4b2f-ac6a-1e2a9b7b1b6a)

**Comment by Fancazista** [comment]
You can find the answer to your problem here, read carefully what is written. Depending on the inventory you use you must enter the event to disarm the player / if you don't have inventories, use the native one to do it.
 https://github.com/Fancazista/fanca_safezone/blob/main/config.lua#L16

**Comment by PWajong** [comment]
sorry my fault! u can close this, thnx for the fast response!
